// Feuille de style du lecteur ADT (barre d'outils, panneaux, activités, surlignage).
export const RUNTIME_CSS = String.raw`
:root { --adt-bg: #ffffff; --adt-fg: #111827; --adt-muted: #6b7280; --adt-border: #e5e7eb; --adt-accent: #0b6f9e; --adt-accent-fg: #ffffff; --adt-panel: #ffffff; --adt-shadow: 0 10px 30px rgba(0,0,0,.18); --adt-icon: 24px; --dock-height: 64px; --adt-radius: 14px; --adt-focus: #f59e0b; }
body[adt-theme="dark"] { --adt-bg: #111827; --adt-fg: #f3f4f6; --adt-muted: #9ca3af; --adt-border: #374151; --adt-panel: #1f2937; --adt-shadow: 0 10px 30px rgba(0,0,0,.5); }
body[icon-size="sm"] { --adt-icon: 20px; } body[icon-size="lg"] { --adt-icon: 30px; }
body[reduce-motion="true"] *, body[reduce-motion="true"] *::before, body[reduce-motion="true"] *::after { transition: none !important; animation: none !important; scroll-behavior: auto !important; }
body { padding-bottom: calc(var(--dock-height) + 16px); }
body[nav-position="top"] { padding-bottom: 0; padding-top: calc(var(--dock-height) + 16px); }
body[data-activity-dock="true"] { padding-bottom: calc(var(--dock-height) + 84px); }
.sr-only { position: absolute !important; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }
.adt-skip { position: absolute; left: 8px; top: -60px; z-index: 100; background: var(--adt-accent); color: var(--adt-accent-fg); padding: 8px 14px; border-radius: 8px; font: 600 15px system-ui, sans-serif; } .adt-skip:focus { top: 8px; }
#interface-container, #nav-container { font-family: "Atkinson Hyperlegible", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; color: var(--adt-fg); }
.adt-dock { position: fixed; left: 0; right: 0; bottom: 0; z-index: 60; display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 8px 12px; background: var(--adt-panel); border-top: 1px solid var(--adt-border); box-shadow: 0 -4px 24px rgba(0,0,0,.08); transition: transform .25s ease, opacity .25s ease; }
body[nav-position="top"] .adt-dock { top: 0; bottom: auto; border-top: 0; border-bottom: 1px solid var(--adt-border); }
body[nav-size="compact"] .adt-dock { left: 50%; right: auto; transform: translateX(-50%); width: min(96vw, 820px); margin-bottom: 10px; border-radius: var(--adt-radius); border: 1px solid var(--adt-border); }
body[nav-position="top"][nav-size="compact"] .adt-dock { margin-top: 10px; }
body[nav-align="center"] .adt-dock { justify-content: center; } body[nav-align="center"] .adt-dock-left { display: none; }
.adt-dock-hidden { transform: translateY(110%); opacity: 0; } body[nav-position="top"] .adt-dock-hidden { transform: translateY(-110%); } body[nav-size="compact"] .adt-dock-hidden { transform: translateX(-50%) translateY(110%); }
.adt-dock-left, .adt-dock-center, .adt-dock-right { display: flex; align-items: center; gap: 6px; min-width: 0; }
.adt-dock-left { flex: 1 1 0; } .adt-dock-right { flex: 1 1 0; justify-content: flex-end; }
.adt-dock-btn { display: inline-flex; align-items: center; gap: 8px; min-width: 44px; min-height: 44px; padding: 8px; border: 0; border-radius: 10px; background: transparent; color: var(--adt-fg); cursor: pointer; font: inherit; }
.adt-dock-btn svg { width: var(--adt-icon); height: var(--adt-icon); flex: none; }
.adt-dock-btn:hover { background: rgba(28,171,226,.12); } .adt-dock-btn:focus-visible, .adt-btn:focus-visible, .adt-choice:focus-visible, .adt-seg:focus-visible, .adt-tab:focus-visible, .glossary-term:focus-visible { outline: 3px solid var(--adt-focus); outline-offset: 2px; }
.adt-dock-btn[aria-pressed="true"] { background: var(--adt-accent); color: var(--adt-accent-fg); }
.adt-dock-title { font-size: 15px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 28vw; }
@media (max-width: 640px) { .adt-dock-title { display: none; } .adt-dock { padding: 6px; gap: 2px; } }
.adt-page-indicator { font-size: 15px; font-variant-numeric: tabular-nums; min-width: 9ch; text-align: center; }
.adt-panel-host { position: fixed; z-index: 70; left: 0; right: 0; bottom: var(--dock-height); display: flex; justify-content: flex-end; padding: 12px; pointer-events: none; }
body[nav-position="top"] .adt-panel-host { bottom: auto; top: var(--dock-height); }
.adt-panel { pointer-events: auto; width: min(420px, 94vw); max-height: min(70vh, 640px); overflow: auto; background: var(--adt-panel); color: var(--adt-fg); border: 1px solid var(--adt-border); border-radius: var(--adt-radius); box-shadow: var(--adt-shadow); }
.adt-panel-head { position: sticky; top: 0; display: flex; align-items: center; justify-content: space-between; padding: 12px 16px; background: var(--adt-panel); border-bottom: 1px solid var(--adt-border); z-index: 1; }
.adt-panel-head h2 { margin: 0; font-size: 17px; } .adt-panel-body { padding: 14px 16px 18px; display: flex; flex-direction: column; gap: 10px; }
.adt-close { min-width: 36px; min-height: 36px; } .adt-close svg { width: 20px; height: 20px; }
.adt-toc { list-style: none; margin: 0; padding: 0; } .adt-toc li a { display: block; padding: 8px 10px; border-radius: 8px; color: inherit; text-decoration: none; } .adt-toc li a:hover { background: rgba(28,171,226,.12); } .adt-toc li a[aria-current="page"] { background: var(--adt-accent); color: var(--adt-accent-fg); }
.adt-toc-l2 a { padding-left: 24px !important; } .adt-toc-l3 a { padding-left: 38px !important; } .adt-toc-l4 a, .adt-toc-l5 a, .adt-toc-l6 a { padding-left: 52px !important; }
.adt-row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 6px 0; font-size: 15px; } .adt-row-col { flex-direction: column; align-items: stretch; gap: 6px; }
.adt-switch { appearance: none; width: 44px; height: 26px; border-radius: 13px; background: #cbd5e1; position: relative; cursor: pointer; flex: none; transition: background .2s; } .adt-switch::after { content: ""; position: absolute; top: 3px; left: 3px; width: 20px; height: 20px; border-radius: 50%; background: #fff; transition: transform .2s; } .adt-switch:checked { background: var(--adt-accent); } .adt-switch:checked::after { transform: translateX(18px); } .adt-switch:disabled { opacity: .5; }
.adt-segmented { display: flex; gap: 4px; background: rgba(127,127,127,.12); padding: 4px; border-radius: 10px; } .adt-seg { flex: 1; min-height: 36px; border: 0; border-radius: 8px; background: transparent; color: inherit; font: inherit; cursor: pointer; } .adt-seg-on { background: var(--adt-panel); font-weight: 700; box-shadow: 0 1px 3px rgba(0,0,0,.15); }
.adt-settings-section { border-top: 1px solid var(--adt-border); padding-top: 8px; } .adt-settings-section h3 { margin: 0 0 4px; font-size: 13px; text-transform: uppercase; letter-spacing: .04em; color: var(--adt-muted); }
.adt-shortcuts { margin: 0; padding: 0 0 0 4px; list-style: none; display: grid; gap: 4px; font-size: 14px; } kbd { font: 600 12px ui-monospace, monospace; background: rgba(127,127,127,.15); border-radius: 4px; padding: 1px 6px; }
.adt-choice { display: flex; align-items: center; gap: 10px; width: 100%; min-height: 44px; padding: 8px 12px; border: 1px solid var(--adt-border); border-radius: 10px; background: transparent; color: inherit; font: inherit; text-align: left; cursor: pointer; } .adt-choice-on { border-color: var(--adt-accent); background: rgba(28,171,226,.12); font-weight: 700; }
.adt-lang-list { display: flex; flex-direction: column; gap: 6px; }
.adt-btn { min-height: 44px; padding: 10px 18px; border: 0; border-radius: 12px; background: var(--adt-accent); color: var(--adt-accent-fg); font: 600 16px inherit; cursor: pointer; } .adt-btn:disabled { opacity: .45; cursor: not-allowed; } .adt-btn-ghost { background: transparent; color: var(--adt-fg); border: 1px solid var(--adt-border); } .adt-btn-sm { min-height: 34px; padding: 4px 12px; font-size: 14px; } .adt-next { background: #16a34a; }
.adt-input, .adt-select { min-height: 40px; padding: 6px 10px; border: 1px solid var(--adt-border); border-radius: 8px; background: var(--adt-bg); color: var(--adt-fg); font: inherit; }
.adt-tabs { display: flex; gap: 6px; } .adt-tab { flex: 1; min-height: 38px; border: 1px solid var(--adt-border); border-radius: 8px; background: transparent; color: inherit; font: inherit; cursor: pointer; } .adt-tab-on { background: var(--adt-accent); color: var(--adt-accent-fg); border-color: var(--adt-accent); }
.adt-glossary-list { display: flex; flex-direction: column; gap: 6px; } .adt-term { border: 1px solid var(--adt-border); border-radius: 10px; padding: 6px 10px; } .adt-term summary { cursor: pointer; font-weight: 700; display: flex; gap: 8px; align-items: center; min-height: 32px; } .adt-term p { margin: 6px 0; } .adt-term-img, .adt-popover-img { max-width: 100%; border-radius: 8px; margin-top: 6px; } .adt-term-video, .adt-popover-video { width: 100%; border-radius: 8px; margin-top: 6px; }
.adt-emoji { font-size: 1.2em; } .adt-muted { color: var(--adt-muted); font-size: 14px; }
.glossary-term { background: rgba(16,185,129,.18); color: inherit; border-radius: 4px; cursor: pointer; padding: 0 2px; border-bottom: 2px solid rgba(5,150,105,.6); }
.glossary-flash { animation: adt-flash 1s ease-in-out 3; } @keyframes adt-flash { 50% { background: #fde047; } }
.adt-popover { position: absolute; z-index: 90; width: min(360px, 92vw); background: var(--adt-panel); color: var(--adt-fg); border: 1px solid var(--adt-border); border-radius: 12px; box-shadow: var(--adt-shadow); padding: 12px 14px; font-family: system-ui, sans-serif; font-size: 16px; } .adt-popover-head { display: flex; align-items: center; gap: 8px; } .adt-popover-head strong { flex: 1; } .adt-popover p { margin: 8px 0; }
.adt-audio-bar { position: fixed; z-index: 65; left: 50%; transform: translateX(-50%); bottom: calc(var(--dock-height) + 8px); display: flex; align-items: center; gap: 4px; padding: 6px 10px; background: var(--adt-panel); border: 1px solid var(--adt-border); border-radius: 14px; box-shadow: var(--adt-shadow); max-width: 96vw; } body[nav-position="top"] .adt-audio-bar { bottom: auto; top: calc(var(--dock-height) + 8px); }
.adt-range { width: 90px; } .adt-audio-pos { font-size: 13px; color: var(--adt-muted); min-width: 5ch; text-align: right; }
.tts-active-block { outline: 3px solid #fde047; outline-offset: 3px; border-radius: 6px; background: rgba(253,224,71,.25); } .tts-word-active { background: #fde047; border-radius: 3px; color: #111; }
.adt-sl-video { position: fixed; z-index: 80; width: min(320px, 60vw); background: #000; border-radius: 12px; overflow: hidden; box-shadow: var(--adt-shadow); cursor: move; touch-action: none; } .adt-sl-video video { display: block; width: 100%; } .adt-sl-video .adt-close { position: absolute; top: 4px; right: 4px; color: #fff; background: rgba(0,0,0,.5); }
.adt-notepad { width: 100%; min-height: 220px; padding: 10px; border: 1px solid var(--adt-border); border-radius: 10px; background: var(--adt-bg); color: var(--adt-fg); font: inherit; resize: vertical; } .adt-eli5 { font-size: 17px; line-height: 1.6; }
.adt-activity-dock { position: fixed; z-index: 58; left: 0; right: 0; bottom: var(--dock-height); display: flex; justify-content: center; gap: 10px; padding: 10px; background: linear-gradient(to top, var(--adt-panel), transparent); } body[nav-position="top"] .adt-activity-dock { bottom: 0; }
.adt-toast { position: fixed; z-index: 95; top: 16px; left: 50%; transform: translateX(-50%); padding: 12px 18px; border-radius: 12px; background: #1f2937; color: #fff; font: 600 16px system-ui, sans-serif; box-shadow: var(--adt-shadow); transition: opacity .4s; } .adt-toast-success { background: #15803d; } .adt-toast-warning { background: #b45309; } .adt-toast-out { opacity: 0; }
.adt-confetti { position: fixed; inset: 0; z-index: 99; pointer-events: none; }
.adt-tutorial { position: fixed; inset: 0; z-index: 98; display: flex; align-items: center; justify-content: center; background: rgba(0,0,0,.55); } .adt-tutorial-card { width: min(440px, 92vw); background: var(--adt-panel); color: var(--adt-fg); padding: 22px; border-radius: 16px; box-shadow: var(--adt-shadow); font-family: system-ui, sans-serif; } .adt-tutorial-card h2 { margin-top: 0; }
.adt-correct, label.adt-correct, .activity-option.adt-correct { border-color: #16a34a !important; background-color: rgba(22,163,74,.10) !important; } .adt-incorrect, label.adt-incorrect, .activity-option.adt-incorrect { border-color: #dc2626 !important; background-color: rgba(220,38,38,.08) !important; } .adt-gibberish { border-color: #ea580c !important; } .adt-profanity { border-color: #dc2626 !important; background-color: rgba(220,38,38,.12) !important; }
input.adt-correct, textarea.adt-correct { border: 2px solid #16a34a !important; } input.adt-incorrect, textarea.adt-incorrect { border: 2px solid #dc2626 !important; }
.feedback-container.adt-auto { display: inline-flex; align-items: center; gap: 6px; margin-left: 8px; font: 600 14px system-ui, sans-serif; } .adt-fb-correct { color: #15803d; } .adt-fb-incorrect, .adt-fb-profanity { color: #b91c1c; } .adt-fb-gibberish { color: #c2410c; }
.adt-badge { display: inline-flex; align-items: center; justify-content: center; margin-left: 4px; width: 20px; height: 20px; border-radius: 50%; font-size: 13px; font-weight: 700; color: #fff; } .adt-badge-ok { background: #16a34a; } .adt-badge-ko { background: #dc2626; }
.selected-option { outline: 2px solid var(--adt-accent); } .adt-selected { outline: 3px solid var(--adt-accent); outline-offset: 2px; } .adt-dragover { background: rgba(28,171,226,.15) !important; }
.fitb-inline-input { display: inline-block; min-height: 2em; padding: 0 .4em; margin: 0 .15em; border: 0; border-bottom: 2px solid #64748b; background: rgba(28,171,226,.06); font: inherit; color: inherit; border-radius: 4px 4px 0 0; } .fitb-inline-input:focus { outline: 3px solid var(--adt-focus); }
.adt-order-controls { display: inline-flex; gap: 4px; margin-left: 8px; } .adt-order-controls button { min-width: 36px; min-height: 36px; border: 1px solid var(--adt-border); border-radius: 8px; background: var(--adt-panel); color: inherit; cursor: pointer; }
.placed-in-dropzone, .placed-word { background-color: rgba(59,130,246,.12) !important; }
.adt-step-prompt { display: flex; flex-direction: column; gap: 10px; margin: 12px 0; } .adt-step-feedback { font-weight: 600; min-height: 1.5em; }
@media print { .adt-dock, .adt-panel-host, .adt-audio-bar, .adt-activity-dock, .adt-skip { display: none !important; } }
`;
