// Liste de contrôle du réviseur (validation manuelle), en français.
export const REVIEWER_CATALOG = {
  identification_fields: [
    { id: "reviewer-name", label: "Nom du réviseur", type: "text", required: true },
    { id: "institution", label: "Institution", type: "text", required: false },
    { id: "start-page", label: "Première page validée", description: "Première page du livre numérique incluse dans cette revue.", type: "number", required: false },
    { id: "end-page", label: "Dernière page validée", description: "Dernière page du livre numérique incluse dans cette revue.", type: "number", required: false },
    { id: "start-date", label: "Date de début", type: "date", required: false },
    { id: "end-date", label: "Date de fin", type: "date", required: false },
    { id: "comments", label: "Commentaires", description: "Remarques générales sur la session de revue.", type: "textarea", required: false },
  ],
  instructions: [
    { id: "objective", title: "Objectif de la validation", body: "Évaluer la qualité du contenu et l'accessibilité de l'ADT, identifier les problèmes ou pistes d'amélioration et confirmer que le livre empaqueté correspond fidèlement à la source, répond aux exigences d'accessibilité, s'aligne sur la conception universelle de l'apprentissage et respecte les normes internationales.", bullets: ["Correspond fidèlement au contenu du livre d'origine.", "Répond aux exigences minimales d'accessibilité.", "S'aligne sur les principes de la conception universelle de l'apprentissage (CUA).", "Respecte les normes internationales d'accessibilité."] },
    { id: "workflow", title: "Déroulement recommandé", body: "Renseignez d'abord l'identification du réviseur, lisez les consignes de chaque domaine, puis validez page par page en notant des commentaires clairs et des propositions de modification.", bullets: ["Remplir l'identification avant de valider.", "Lire les consignes des domaines avant de commencer.", "Noter le lien de la page ADT et son numéro pour chaque constat.", "Décrire clairement le problème et proposer une modification quand c'est possible."] },
  ],
  sections: [
    { id: "text-extracted-accuracy", label: "Fidélité du texte extrait", criteria: [
      { id: "text-matches-original-reading-order", label: "Le texte extrait correspond à l'original et conserve l'ordre de lecture.", guidance: "Le texte doit correspondre intégralement au contenu d'origine sans omission, ajout ni altération, et suivre une séquence logique.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "text-does-not-break-illogically", label: "Le texte n'est pas découpé en fragments aléatoires ou illogiques.", guidance: "Le texte apparaît en unités cohérentes (phrases, paragraphes) plutôt qu'en caractères, mots ou segments isolés.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
    { id: "visual-media-image-description", label: "Médias visuels et description des images", criteria: [
      { id: "images-match-original-framing", label: "Les images extraites correspondent à l'original et conservent cadrage et proportions.", guidance: "Les images doivent correspondre exactement à celles du PDF : cadre, résolution, proportions, couleurs, sans distorsion ni recadrage indu.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "text-not-in-image-format", label: "Aucun texte signifiant n'est conservé sous forme d'image.", guidance: "Le texte associé aux images doit être séparé et présenté en texte sélectionnable.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "illustrations-remain-consistent", label: "Les illustrations décrivant objets, lieux et personnages sont cohérentes.", guidance: "Un même personnage, objet ou lieu conserve le même style d'illustration.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false },
      { id: "meaningful-graphics-have-descriptions", label: "Tout contenu graphique signifiant est accompagné d'une description.", guidance: "Chaque élément visuel signifiant (image, schéma, vidéo) possède une description exacte qui fonctionne.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "decorative-images-do-not-use-description", label: "Les images décoratives n'ont pas de description.", guidance: "Les images décoratives ou non essentielles sont masquées aux lecteurs d'écran.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false },
      { id: "image-description-reflects-purpose-context", label: "La description reflète fidèlement le but et le contexte de l'image (concise et claire).", guidance: "Les descriptions sont concises, claires et centrées sur l'information utile à la compréhension pédagogique.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "image-description-style-consistent", label: "Le style des descriptions est homogène dans tout le livre.", guidance: "Format, ton et niveau de détail suivent un style cohérent.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false } ] },
    { id: "audio-voice-over", label: "Audio et voix", criteria: [
      { id: "audio-available-for-relevant-content", label: "L'audio est disponible pour tout le contenu pertinent.", guidance: "Titres, numéros de page, contenu principal, références, boutons de navigation et consignes disposent d'un audio.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "audio-synchronized-with-highlighted-text", label: "L'audio est synchronisé avec le texte surligné.", guidance: "La lecture commence et progresse en phase avec le surlignage.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
    { id: "easy-read", label: "Lecture facile", criteria: [
      { id: "easy-read-preserves-key-information", label: "La lecture facile simplifie la langue en préservant les informations clés et la valeur pédagogique.", guidance: "Objectifs, consignes et concepts essentiels restent intacts.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "easy-read-uses-present-active-voice", label: "La lecture facile est rédigée au présent et à la voix active.", guidance: "La voix active améliore la clarté et la compréhension.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "numbers-preserved-as-numerals", label: "Les nombres sont conservés en chiffres.", guidance: "Par exemple « 5 » plutôt que « cinq ».", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false } ] },
    { id: "glossary", label: "Glossaire", criteria: [
      { id: "glossary-includes-relevant-key-terms", label: "Le glossaire contient les mots clés, la nouvelle terminologie et les concepts ; pas de mots non pertinents.", guidance: "Le glossaire couvre les mots, concepts et termes clés ou peu familiers.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "glossary-links-open-without-issues", label: "Les termes sont liés au glossaire et s'ouvrent sans problème.", guidance: "La fenêtre ou le panneau apparaît immédiatement, est entièrement visible et ne masque pas le contenu essentiel.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
    { id: "interactivity", label: "Interactivité", criteria: [
      { id: "all-exercises-interactive", label: "Tous les exercices sont interactifs.", guidance: "Aucun exercice n'est laissé en texte statique.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "exercises-have-clear-instructions", label: "Chaque exercice a des consignes claires sur la même page.", guidance: "L'apprenant comprend ce qu'il doit faire sans quitter la page.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "exercises-provide-feedback", label: "Les exercices donnent un retour après validation.", guidance: "Un retour explicite indique la réussite ou l'erreur.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "blanks-not-misidentified", label: "Les espaces à compléter ne sont pas pris pour du texte.", guidance: "Les blancs deviennent des champs de saisie.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false },
      { id: "exercise-design-consistent", label: "La conception des exercices est cohérente dans tout l'ADT.", guidance: "Même apparence et même fonctionnement d'une activité à l'autre.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false },
      { id: "answers-not-given", label: "Les réponses ne sont pas dévoilées dans le texte ou les contenus d'accessibilité.", guidance: "Ni le texte, ni les descriptions d'images, ni la lecture facile ne révèlent les réponses.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
    { id: "typography-layout", label: "Typographie, mise en page et lisibilité", criteria: [
      { id: "layout-maintains-learning-flow", label: "La mise en page conserve le déroulé pédagogique du livre d'origine.", guidance: "L'ordre et la hiérarchie des contenus sont respectés.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "font-supports-readability", label: "La police et sa taille favorisent la lisibilité et l'organisation du contenu.", guidance: "Tailles suffisantes, hiérarchie visible, contraste adapté.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
    { id: "instructional-content-design", label: "Conception du contenu pédagogique", criteria: [
      { id: "inclusive-language", label: "Le langage est inclusif dans tout le contenu.", guidance: "Pas de stéréotypes ni de formulations excluantes.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "no-typos", label: "Le contenu est exempt de fautes de frappe, d'orthographe et de grammaire.", guidance: "Relire attentivement textes, légendes et consignes.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "key-points-summarized", label: "Les points clés sont résumés en fin de chapitre.", guidance: "Lorsque le livre d'origine le prévoit.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false },
      { id: "language-appropriate", label: "La langue est adaptée à l'âge, au niveau et au contexte.", guidance: "Vocabulaire et complexité adaptés au public.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "terminology-consistent", label: "La terminologie est utilisée de façon cohérente.", guidance: "Même terme pour le même concept dans tout le livre.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
    { id: "translation", label: "Traduction", criteria: [
      { id: "translation-accurate", label: "La traduction est exacte, fluide et préserve le sens et la complexité.", guidance: "Pas d'omission ni d'ajout, registre adapté.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "all-text-translated", label: "Tout le texte est traduit.", guidance: "Aucun segment ne reste dans la langue source.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "layout-preserved", label: "La mise en page et la structure sont préservées.", guidance: "Le passage d'une langue à l'autre ne casse pas la page.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "translation-cross-device", label: "La traduction fonctionne sur tous les appareils et navigateurs.", guidance: "Tester sur mobile et ordinateur.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false },
      { id: "translation-loads", label: "La traduction se charge correctement et rapidement.", guidance: "Pas de délai excessif ni d'erreur.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: false } ] },
    { id: "sign-language", label: "Vidéo (langue des signes)", criteria: [
      { id: "signing-fully-visible", label: "Les mouvements et expressions faciales sont entièrement visibles.", guidance: "Cadrage complet du haut du corps.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "background-attire", label: "L'arrière-plan et la tenue ne distraient pas de la signation.", guidance: "Fond uni, vêtements contrastés.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "local-sign-language", label: "La langue des signes locale est utilisée.", guidance: "Par exemple la LSF pour la France.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "narrator-visible", label: "L'interprète est bien visible, avec un contraste et un éclairage appropriés.", guidance: "Lumière uniforme, pas de contre-jour.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true },
      { id: "subtitles-reflect-interpretation", label: "Les sous-titres reflètent l'interprétation en langue des signes, non le texte mot à mot.", guidance: "Les sous-titres suivent le sens signé.", requires_comment_on_failure: true, requires_suggested_modification_on_failure: true } ] },
  ],
};
export const REVIEW_STATUSES = { "not-reviewed": "Non révisé", pass: "Réussite", "needs-changes": "Modifications nécessaires", "not-applicable": "Non applicable" };
